# Generated by Django 4.0.4 on 2022-05-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='product',
            new_name='products',
        ),
    ]
