# Generated by Django 4.0.4 on 2022-05-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
