# Generated by Django 4.0.4 on 2022-05-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
