# Generated by Django 4.0.4 on 2022-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_contactus_is_replied_alter_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reply',
            field=models.TextField(default='no-reply', max_length=1000),
        ),
    ]
